name: Build Zephyr binary

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-container:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v3
        with:
          tags: build-image:latest
          push: false

  build-binary:
    name: Build Zephyr Binary
    runs-on:
    ubuntu-latest: build-image:latest
    steps:
      - run: ls