name: Build Zephyr binary

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-container:
    runs-on: ubuntu-latest
    name: Build Zephyr binary
    steps:
      - uses: actions/checkout@v3
      - name: GH step
        uses: ./zephyr-container.yml