name: Build Zephyr binary

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-ci:
    name: Build Zephyr binary
    runs:
      using: 'docker'
      image: 'Dockerfile'