name: Build Zephyr binary

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-container:
    image: Dockerfile

  steps:
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2